[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "slam-docs"
authors = [{name = "haohaoalt", email = "haohaoalt@163.com"}]
dynamic = ["version", "description"]
